### ISSUE TITLE
can not compile on kernel 5.10.69-1-lts and 5.14.8

### ISSUE THREAD

**Issue by idreamerhx** [Open-CAS/open-cas-linux#968]
Linux xxx 5.10.69-1-lts #1 SMP Sun, 26 Sep 2021 12:30:37 +0000 x86_64 GNU/Linux

branch: master
./configure
make

/opt/open-cas-linux/modules/cas_cache/src/ocf/metadata/metadata_io.c:535:34: error: 'env_mpool_create' reading 32 bytes from a region of size 28 [-Werror=stringop-overread]
  535 |         ocf_ctx->resources.mio = env_mpool_create(
      |                                  ^~~~~~~~~~~~~~~~~
  536 |                         sizeof(struct metadata_io_request_asynch),
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  537 |                         sizeof(struct metadata_io_request),
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  538 |                         ENV_MEM_NOIO, ocf_mio_size_max - 1, true,
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  539 |                         limits,
      |                         ~~~~~~~
  540 |                         "ocf_mio",
      |                         ~~~~~~~~~~
  541 |                         true);
      |                         ~~~~~

5.14.8

./configure

disk_part_iter_next not find

**Comment by kmajzero** [comment]
Could you please add some information about your environment, especially:
* compiler used, compiler version, extra flags used if any
* distribution used
* kernel used - vanilla, distro-supplied, custom. If custom, please include the summary of patches applied

Please be advised that OpenCAS supports kernels up to 5.11 only. Support for newer kernels is in progress.

**Comment by idreamerhx** [comment]
Hi~   I will add these information as soon as possible.

**Comment by kmajzero** [comment]
GCC 11 compilation issue was fixed. Patch was merged to master

Newer kernel support is in progress. Any updates will land in #987
