### ISSUE TITLE
Does not compile with Linux 5.8.9

### ISSUE THREAD

**Issue by cHolzberger** [Open-CAS/open-cas-linux#525]
/usr/src/open-cas-linux-v20.03.2.0295/configure.d/1_generic_acct.conf_dir/test_mod.c:7:1: error: implicit declaration of function ‘generic_start_io_acct’ [-Werror=implicit-function-declaration]
    7 | generic_start_io_acct(NULL, 0, 0, NULL);

generic_start_io_acct has been removed starting with 5.8

**Comment by anatol** [comment]
Here is the compilation failure at Arch Linux with 5.8 kernel

```
### generic_start_io_acct(NULL, 0, 0, NULL) ###
make: Entering directory '/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir'
make -C /lib/modules/5.8.12-arch1-1/build/ M=/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir modules
make[1]: Entering directory '/usr/lib/modules/5.8.12-arch1-1/build'
  CC [M]  /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.o
/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.c: In function ‘init_module’:
/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.c:7:1: error: implicit declaration of function ‘generic_start_io_acct’ [-Werror=implicit-function-declaration]
    7 | generic_start_io_acct(NULL, 0, 0, NULL);
      | ^~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:281: /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.o] Error 1
make[1]: *** [Makefile:1752: /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.8.12-arch1-1/build'
make: *** [Makefile:12: all] Error 2
make: Leaving directory '/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir'
### generic_start_io_acct(0, 0, NULL) ###
make: Entering directory '/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir'
make -C /lib/modules/5.8.12-arch1-1/build/ M=/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir modules
make[1]: Entering directory '/usr/lib/modules/5.8.12-arch1-1/build'
  CC [M]  /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.o
/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.c: In function ‘init_module’:
/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.c:8:1: error: implicit declaration of function ‘generic_start_io_acct’ [-Werror=implicit-function-declaration]
    8 | generic_start_io_acct(0, 0, NULL);
      | ^~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:281: /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.o] Error 1
make[1]: *** [Makefile:1752: /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.8.12-arch1-1/build'
make: *** [Makefile:12: all] Error 2
make: Leaving directory '/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir'
### part_round_stats(1, 1) ###
make: Entering directory '/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir'
make -C /lib/modules/5.8.12-arch1-1/build/ M=/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir modules
make[1]: Entering directory '/usr/lib/modules/5.8.12-arch1-1/build'
  CC [M]  /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.o
/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.c: In function ‘init_module’:
/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.c:9:1: error: implicit declaration of function ‘part_round_stats’ [-Werror=implicit-function-declaration]
    9 | part_round_stats(1, 1);
      | ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:281: /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.o] Error 1
make[1]: *** [Makefile:1752: /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.8.12-arch1-1/build'
make: *** [Makefile:12: all] Error 2
make: Leaving directory '/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir'
### part_round_stats(NULL, 1, 1) ###
make: Entering directory '/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir'
make -C /lib/modules/5.8.12-arch1-1/build/ M=/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir modules
make[1]: Entering directory '/usr/lib/modules/5.8.12-arch1-1/build'
  CC [M]  /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.o
/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.c: In function ‘init_module’:
/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.c:10:1: error: implicit declaration of function ‘part_round_stats’ [-Werror=implicit-function-declaration]
   10 | part_round_stats(NULL, 1, 1);
      | ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:281: /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir/test_mod.o] Error 1
make[1]: *** [Makefile:1752: /mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.8.12-arch1-1/build'
make: *** [Makefile:12: all] Error 2
make: Leaving directory '/mnt/cold/sources/open-cas-linux/configure.d/1_generic_acct.conf_dir'
```

It fails to find 2 functions: `generic_start_io_acct` and `part_round_stats`



function `generic_start_io_acct` got removed in https://github.com/torvalds/linux/commit/e722fff238bbfe6308d7778a8c2163c181bf998a

The clients moved to the new API. Here are examples how it was done
https://github.com/torvalds/linux/commit/d7614e4480fad946ceb1f3f7003850497549d73f
https://github.com/torvalds/linux/commit/0fd92f89a44d3ba32c1056f3ceaba8f8bdc08712
https://github.com/torvalds/linux/commit/86240d5b6813d6855845959b133d5b4a95c60f92
https://github.com/torvalds/linux/commit/85750aeb748fd17a393d1f510f7b33e3336c395e


`part_round_stats` got removed in https://github.com/torvalds/linux/commit/5b18b5a737600fd20ba2045f320d5926ebbf341a

**Comment by anatol** [comment]
Is there any chance you can look at porting it to the new kernel API changes? It will help to use this project at systems with up-to-date kernels (like mine Arch Linux).

Besides that Ubuntu 20.10 with linux 5.8 got released already.

**Comment by anatol** [comment]
I looked at this issue. Upstream linux modified block device API a lot.
* Some of the change like removed `generic_start_io_acct()` is relatively simple - there is `data->start_time = bio_start_io_acct(bio);` that seems like an equivalent of `_blockdev_start_io_acct(bio);`.
* `__vmalloc()` dropped the third parameter that seems always `PAGE_KERNEL`
* a few functions have moved to `linux/blkdev.h` thus this header has to be included
* `ioctl_by_bdev()` is removed and now one has to use kernel API directly. So for `ioctl_by_bdev(bdev, BLKRRPART, (unsigned long)NULL);` that's gonna be `bdev_disk_changed(bdev, false);`
* `ioctl_by_bdev(bd, BLKPG, (unsigned long) &barg);` has an equivalent of `bdev_del_partition(bd, part_no);` but the problem is that `bdev_del_partition` is not part of kernel API, there seems no way for a third-party driver to use this function :(
* the same problem with `ioctl_by_bdev(bdev, NVME_IOCTL_ID, (unsigned long)NULL);` functionality that is not exposed via a public kernel API.

I think one should contact maillist, Christoph Hellwig and @axboe to clarify how to migrate the latter 2 function calls.

**Comment by arutk** [comment]
Thank you for your analysis @anatol. Regarding the removal of ioctl_by_bdev. All the instances related to NVME support (e.g. NVME_IOCTL_ID) are related to CAS atomic metadata feature, where metadata is interleaved with data using extended LBA (512B + 8B) drive capability. CAS atomic mode worked only on older kernels. Assuming the underlying cache drives are configured with standard sector size you can safely disable CAS_NVME_PARTIAL in config.mk. If I recall correctly this should remove all calls to ioctl_by_bdev calls related to atomic mode. CAS_NVME_PARTIAL flag indicates that CAS is capable of querying device format and rejecting to start in case of non-standard modes. 

So, from what you wrote, it looks like disabling CAS_NVME_PARTIAL on kernels with missing ioctl_by_bdev would be the only way we can work around missing ioctl_by_bdev(NVME_IOCTL_ID).

**Comment by arutk** [comment]
Fixed by #600
