### ISSUE TITLE
Compilation error on kernel 5.13

### ISSUE THREAD

**Issue by Aste88** [Open-CAS/open-cas-linux#992]
## Description
Building on proxmox 7.1 (kernel 5.13). Kinda worked on pve 7.0 (k 5.11).

Both require modifying config.d/1_bd_first_part.conf and commenting lines #12 tp 21 (checking if disk_part_iter_next returns struct block_device or hd_struct).

## Expected Behavior
build :)

## Actual Behavior
Updating to 5.13 even while patching config.d/1_bd_first_part.conf gives errors during make phase

/root/open-cas-linux/modules/cas_cache/ocf_env.h: In function ‘env_get_free_memory’:
/root/open-cas-linux/modules/cas_cache/ocf_env.h:25:9: error: implicit declaration of function ‘cas_global_zone_page_state’; did you mean ‘global_zone_page_state’? [-Werror=implicit-function-declaration]
   25 |  return cas_global_zone_page_state(NR_FREE_PAGES) << PAGE_SHIFT;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |         global_zone_page_state
/root/open-cas-linux/modules/cas_cache/ocf_env.h: In function ‘env_vmalloc_flags’:
/root/open-cas-linux/modules/cas_cache/ocf_env.h:45:9: error: implicit declaration of function ‘cas_vmalloc’ [-Werror=implicit-function-declaration]
   45 |  return cas_vmalloc(size, flags | __GFP_HIGHMEM);
      |         ^~~~~~~~~~~
/root/open-cas-linux/modules/cas_cache/ocf_env.h:45:9: error: returning ‘int’ from a function with return type ‘void *’ makes pointer from integer without a cast [-Werror=int-conversion]
   45 |  return cas_vmalloc(size, flags | __GFP_HIGHMEM);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/open-cas-linux/modules/cas_cache/ocf_env.h: In function ‘env_get_tick_count’:
/root/open-cas-linux/modules/cas_cache/ocf_env.h:524:2: error: implicit declaration of function ‘CAS_GET_CURRENT_TIME’ [-Werror=implicit-function-declaration]
  524 |  CAS_GET_CURRENT_TIME(&ts);
      |  ^~~~~~~~~~~~~~~~~~~~
In file included from /root/open-cas-linux/modules/cas_cache/cas_cache.h:16,
                 from /root/open-cas-linux/modules/cas_cache/main.c:6:
/root/open-cas-linux/modules/cas_cache/layer_cache_management.h: At top level:
/root/open-cas-linux/modules/cas_cache/layer_cache_management.h:52:10: error: ‘struct ocf_mngt_cache_attach_config’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
   52 |   struct ocf_mngt_cache_attach_config *attach_cfg,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/open-cas-linux/modules/cas_cache/layer_cache_management.h:65:10: error: ‘struct ocf_mngt_cache_attach_config’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
   65 |   struct ocf_mngt_cache_attach_config *attach_cfg,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/open-cas-linux/modules/cas_cache/main.c: In function ‘cas_casdisk_lookup_funtions’:
/root/open-cas-linux/modules/cas_cache/main.c:86:14: error: ‘module_mutex’ undeclared (first use in this function); did you mean ‘module_put’?
   86 |  mutex_lock(&module_mutex);
      |              ^~~~~~~~~~~~
      |              module_put
/root/open-cas-linux/modules/cas_cache/main.c:86:14: note: each undeclared identifier is reported only once for each function it appears in

## Steps to Reproduce
1. use proxmox 7.1 or aany distrp with 5.13
2. patch configure file
3. run make
4. hit error

## Context
error compiling kernel module for 5.13

## Possible Fix
Wish I could help but I have little knowledge of linux kernel

## Your Environment
* OpenCAS version (commit hash or tag):  v21.6.1, master
* Operating System: debian 10 based proxmox 7.1
* Kernel version: 5.13
* Cache device type (NAND/Optane/other): plp nvme
* Core device type (HDD/SSD/other): sas hdd 2tb
* Cache configuration: 1 cache per machine, 3/6 core per cache
* * Cache mode: (default: wt) wb

**Comment by kmajzero** [comment]
Hey,
OpenCAS supports vanilla kernels up to 5.11. 
Support for newer kernels is under way and is tracked by #987 .
